# Generated by Django 5.2.4 on 2025-07-08 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('destinatario', models.CharField(max_length=255, verbose_name='Destinatario')),
                ('movimientos_ids', models.TextField(help_text='IDs de los movimientos de salida, separados por comas')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes', verbose_name='Código QR')),
            ],
            options={
                'verbose_name': 'Guía de Salida',
                'verbose_name_plural': 'Guías de Salida',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU (Código de Artículo)')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción/Motivo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
            },
        ),
    ]
