# Generated by Django 5.2.4 on 2025-08-06 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recepcion', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nro. Recepción')),
                ('fecha_recepcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('orden_asociada', models.CharField(blank=True, max_length=100, verbose_name='N° Orden Asociada')),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=255, verbose_name='Ubicación dentro del Almacén')),
                ('estado_mercancia', models.CharField(blank=True, max_length=255, verbose_name='Estado de la Mercancía')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('nombre_conductor', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Conductor')),
                ('ci_conductor', models.CharField(blank=True, max_length=20, verbose_name='C.I. Conductor')),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Vehículo')),
                ('color_vehiculo', models.CharField(blank=True, max_length=50, verbose_name='Color del Vehículo')),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, verbose_name='Placa del Vehículo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Procesar'), ('parcial', 'Parcialmente Recibida'), ('completa', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado del Acta')),
            ],
            options={
                'verbose_name': 'Acta de Recepción',
                'verbose_name_plural': 'Actas de Recepción',
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Almacén')),
                ('ubicacion', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('cedula_rif', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula/R.I.F.')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Proveedor')),
                ('contacto', models.CharField(blank=True, max_length=255, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Movimiento')),
                ('es_entrada', models.BooleanField(default=False, help_text='Indica si este tipo de movimiento aumenta el stock.')),
                ('es_salida', models.BooleanField(default=False, help_text='Indica si este tipo de movimiento disminuye el stock.')),
                ('es_traslado', models.BooleanField(default=False, help_text='Indica si este tipo de movimiento es un traslado entre almacenes.')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Unidad')),
                ('abreviatura', models.CharField(max_length=10, unique=True, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nro. Cotización')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_validez', models.DateField(blank=True, null=True, verbose_name='Fecha de Validez')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada (Completada)'), ('en_despacho', 'En Despacho Parcial')], default='abierta', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('total_cotizado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Cotizado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='inventario.cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto_cotizado', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Producto Cotizado')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Cotizada')),
                ('cantidad_entregada', models.PositiveIntegerField(default=0, verbose_name='Cantidad Entregada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.cotizacion')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='NotaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_despacho', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nro. Despacho')),
                ('fecha_despacho', models.DateField(auto_now_add=True, verbose_name='Fecha de Despacho')),
                ('orden_asociada', models.CharField(blank=True, max_length=100, verbose_name='N° Orden Asociada')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('nombre_conductor', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Conductor')),
                ('ci_conductor', models.CharField(blank=True, max_length=20, verbose_name='C.I. Conductor')),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Vehículo')),
                ('color_vehiculo', models.CharField(blank=True, max_length=50, verbose_name='Color del Vehículo')),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, verbose_name='Placa del Vehículo')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_despacho_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Nota de Despacho',
                'verbose_name_plural': 'Notas de Despacho',
            },
        ),
        migrations.CreateModel(
            name='GuiaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('destinatario', models.CharField(max_length=255, verbose_name='Destinatario')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes', verbose_name='Código QR')),
                ('acta_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_recepcion_asociadas', to='inventario.actarecepcion', verbose_name='Acta de Recepción Asociada')),
                ('nota_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_salida_asociadas', to='inventario.notadespacho', verbose_name='Nota de Despacho Asociada')),
            ],
            options={
                'verbose_name': 'Guía de Salida',
                'verbose_name_plural': 'Guías de Salida',
            },
        ),
        migrations.CreateModel(
            name='OrdenSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Orden')),
                ('cliente', models.CharField(blank=True, max_length=255, verbose_name='Cliente')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de la Orden')),
                ('cotizacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_salida', to='inventario.cotizacion', verbose_name='Cotización de Origen')),
                ('nota_despacho_asociada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_salida', to='inventario.notadespacho', verbose_name='Nota de Despacho Asociada')),
            ],
            options={
                'verbose_name': 'Orden de Salida',
                'verbose_name_plural': 'Órdenes de Salida',
            },
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='orden_salida_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_despacho_relacionadas', to='inventario.ordensalida', verbose_name='Orden de Salida de Referencia'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SKU (Código de Artículo)')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name='Foto Referencial')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.almacen', verbose_name='Almacén')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor Principal')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.unidadmedida', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('orden_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_orden', to='inventario.ordensalida')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Salida',
                'verbose_name_plural': 'Detalles de Órdenes de Salida',
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto_despacho', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Producto (Despacho)')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('detalle_cotizacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_despacho_asociados', to='inventario.detallecotizacion', verbose_name='Detalle de Cotización de Origen')),
                ('nota_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.notadespacho')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Despacho',
                'verbose_name_plural': 'Detalles de Notas de Despacho',
            },
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='DetalleActaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto_recepcion', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Producto (Recepción)')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('acta_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.actarecepcion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Acta de Recepción',
                'verbose_name_plural': 'Detalles de Actas de Recepción',
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Pago')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Pago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha del Movimiento')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción/Motivo')),
                ('acta_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_agrupados', to='inventario.actarecepcion', verbose_name='Acta de Recepción Asociada')),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventario.almacen', verbose_name='Almacén de Destino')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.almacen', verbose_name='Almacén de Origen')),
                ('guia_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_agrupados', to='inventario.guiasalida', verbose_name='Guía de Salida Asociada')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_producto', to='inventario.producto')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.tipomovimiento', verbose_name='Tipo de Movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
            },
        ),
    ]
