# Generated by Django 5.2.4 on 2025-07-09 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiasalida',
            options={'verbose_name': 'Guía de Salida', 'verbose_name_plural': 'Guías de Saida'},
        ),
        migrations.RemoveField(
            model_name='guiasalida',
            name='movimientos_ids',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='guia_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_agrupados', to='inventario.guiasalida', verbose_name='Guía de Salida Asociada'),
        ),
    ]
