# Generated by Django 5.2.4 on 2025-07-09 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_almacen_proveedor_unidadmedida_producto_stock_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_despacho', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nro. Despacho')),
                ('beneficiario', models.CharField(max_length=255, verbose_name='Nombre del Beneficiario')),
                ('fecha_despacho', models.DateField(auto_now_add=True, verbose_name='Fecha de Despacho')),
                ('orden_asociada', models.CharField(blank=True, max_length=100, verbose_name='N° Orden Asociada')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('nombre_conductor', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Conductor')),
                ('ci_conductor', models.CharField(blank=True, max_length=20, verbose_name='C.I. Conductor')),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Vehículo')),
                ('color_vehiculo', models.CharField(blank=True, max_length=50, verbose_name='Color del Vehículo')),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, verbose_name='Placa del Vehículo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Nota de Despacho',
                'verbose_name_plural': 'Notas de Despacho',
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto_despacho', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Producto (Despacho)')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto')),
                ('nota_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.notadespacho')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Despacho',
                'verbose_name_plural': 'Detalles de Notas de Despacho',
            },
        ),
    ]
