# Generated by Django 5.2.4 on 2025-07-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_notadespacho_detallenotadespacho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiasalida',
            options={'verbose_name': 'Guía de Salida', 'verbose_name_plural': 'Guías de Salida'},
        ),
        migrations.CreateModel(
            name='OrdenSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Orden')),
                ('cliente', models.CharField(blank=True, max_length=255, verbose_name='Cliente')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total de la Orden')),
                ('nota_despacho_asociada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_salida', to='inventario.notadespacho', verbose_name='Nota de Despacho Asociada')),
            ],
            options={
                'verbose_name': 'Orden de Salida',
                'verbose_name_plural': 'Órdenes de Salida',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto')),
                ('orden_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_orden', to='inventario.ordensalida')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Salida',
                'verbose_name_plural': 'Detalles de Órdenes de Salida',
            },
        ),
    ]
