# Generated by Django 5.2.4 on 2025-07-10 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_guiasalida_options_ordensalida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiasalida',
            name='nota_despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_salida_asociadas', to='inventario.notadespacho', verbose_name='Nota de Despacho Asociada'),
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name='Foto Referencial'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.CreateModel(
            name='ActaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recepcion', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nro. Recepción')),
                ('fecha_recepcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('orden_asociada', models.CharField(blank=True, max_length=100, verbose_name='N° Orden Asociada')),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=255, verbose_name='Ubicación dentro del Almacén')),
                ('estado_mercancia', models.CharField(blank=True, max_length=255, verbose_name='Estado de la Mercancía')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('nombre_conductor', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Conductor')),
                ('ci_conductor', models.CharField(blank=True, max_length=20, verbose_name='C.I. Conductor')),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Vehículo')),
                ('color_vehiculo', models.CharField(blank=True, max_length=50, verbose_name='Color del Vehículo')),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, verbose_name='Placa del Vehículo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Acta de Recepción',
                'verbose_name_plural': 'Actas de Recepción',
            },
        ),
        migrations.AddField(
            model_name='guiasalida',
            name='acta_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_recepcion_asociadas', to='inventario.actarecepcion', verbose_name='Acta de Recepción Asociada'),
        ),
        migrations.CreateModel(
            name='DetalleActaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto_recepcion', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Producto (Recepción)')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('acta_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.actarecepcion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Acta de Recepción',
                'verbose_name_plural': 'Detalles de Actas de Recepción',
            },
        ),
    ]
