# Generated by Django 5.2.4 on 2025-07-10 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_cliente_cotizacion_ordensalida_cotizacion_origen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notadespacho',
            name='orden_asociada',
        ),
        migrations.RemoveField(
            model_name='ordensalida',
            name='nota_despacho_asociada',
        ),
        migrations.AddField(
            model_name='detallenotadespacho',
            name='detalle_cotizacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_despachados', to='inventario.detallecotizacion', verbose_name='Detalle de Cotización de Origen'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='orden_salida_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_despacho_generadas', to='inventario.ordensalida', verbose_name='Orden de Salida de Origen'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('aceptada', 'Aceptada'), ('en_despacho', 'En Despacho'), ('cerrada', 'Cerrada (Completada/Cancelada)'), ('rechazada', 'Rechazada')], default='abierta', max_length=20, verbose_name='Estado'),
        ),
    ]
