# Generated by Django 5.2.4 on 2025-07-11 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_notadespacho_orden_asociada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.RemoveField(
            model_name='notadespacho',
            name='orden_salida_origen',
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Procesar'), ('parcial', 'Parcialmente Recibida'), ('completa', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado del Acta'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='acta_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_agrupados', to='inventario.actarecepcion', verbose_name='Acta de Recepción Asociada'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='orden_asociada',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° Orden Asociada'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='orden_salida_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_despacho_relacionadas', to='inventario.ordensalida', verbose_name='Orden de Salida de Referencia'),
        ),
        migrations.AddField(
            model_name='ordensalida',
            name='nota_despacho_asociada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_salida', to='inventario.notadespacho', verbose_name='Nota de Despacho Asociada'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='inventario.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada (Completada)'), ('en_despacho', 'En Despacho Parcial')], default='abierta', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad Cotizada'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='nombre_producto_cotizado',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del Producto Cotizado'),
        ),
        migrations.AlterField(
            model_name='detallenotadespacho',
            name='detalle_cotizacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_despacho_asociados', to='inventario.detallecotizacion', verbose_name='Detalle de Cotización de Origen'),
        ),
        migrations.AlterField(
            model_name='ordensalida',
            name='cotizacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_salida', to='inventario.cotizacion', verbose_name='Cotización de Origen'),
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Pago')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Pago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
