# Generated by Django 5.2.4 on 2025-08-01 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_categoria_remove_notadespacho_beneficiario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notadespacho',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_despacho_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
