version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # Aquí apuntas directamente a la IP del contenedor Debian
      DATABASE_HOST: 10.12.12.34
      DATABASE_PORT: 5432

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    # Si solo quieres que sea accesible por IP interna, puedes quitar el mapeo de puertos
    # ports:
    #   - "5432:5432"
    networks:
      default:
        ipv4_address: 10.12.12.34

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.12.0/24

