# Generated by Django 6.0.6 on 2026-06-09 21:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rif_nit', models.CharField(help_text='Número de identificación fiscal', max_length=50, unique=True, verbose_name='RIF/NIT')),
                ('contacto_principal', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('direccion', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ActaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura_proveedor', models.CharField(max_length=100)),
                ('monto_total_factura', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.CharField(blank=True, default='', max_length=200)),
                ('nro_orden_asociada', models.CharField(blank=True, default='', max_length=100)),
                ('ubicacion_almacen', models.CharField(blank=True, default='', max_length=100)),
                ('estado_mercancia', models.CharField(choices=[('BUENO', 'Buen Estado'), ('CON_OBSERVACIONES', 'Con Observaciones')], default='BUENO', max_length=50)),
                ('nombre_conductor', models.CharField(blank=True, default='', max_length=150)),
                ('cedula_conductor', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_vehiculo', models.CharField(blank=True, default='', max_length=100)),
                ('color_vehiculo', models.CharField(blank=True, default='', max_length=50)),
                ('placa_vehiculo', models.CharField(blank=True, default='', max_length=50)),
                ('beneficiario_autorizado', models.CharField(blank=True, default='', max_length=150)),
                ('cedula_beneficiario', models.CharField(blank=True, default='', max_length=20)),
                ('telefono_beneficiario', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_hora_llegada_conductor', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_llegada_beneficiario', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_recepcion', to='core.almacen')),
            ],
            options={
                'verbose_name_plural': 'Actas de Recepción',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rastreo', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Nro. Nota de Entrega / Cotización')),
                ('referencia_proyecto', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente por despachar'), ('EN_PROCESO', 'En Proceso (Parcialmente Dotado)'), ('DOTADO', 'Dotado (Completado)'), ('ANULADO', 'Anulado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Tasa Cambio BCV')),
                ('observacion_tasa', models.CharField(default='BCV', max_length=100)),
                ('incluye_iva', models.BooleanField(default=True, verbose_name='¿Aplica IVA (16%)?')),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('base_imponible_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_iva_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='core.cliente')),
            ],
            options={
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion_departamento', models.CharField(default='GENERAL', max_length=150)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('costo_base_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de compra del producto en el momento de la cotización', max_digits=12)),
                ('factor_margen', models.DecimalField(decimal_places=2, default=0.1, help_text='Margen sobre el costo (ej. 0.10 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pvp_unitario_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_item_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cantidad_faltante', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('observacion_item', models.CharField(blank=True, default='', max_length=255)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cotizacion')),
            ],
            options={
                'verbose_name_plural': 'Ítems de Cotización',
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='NotaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Nro. Guía / Despacho')),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('nombre_beneficiario', models.CharField(blank=True, default='', max_length=200)),
                ('proveedor_origen', models.CharField(blank=True, default='', max_length=200)),
                ('nro_orden_asociada', models.CharField(blank=True, default='', max_length=100)),
                ('nombre_conductor', models.CharField(blank=True, default='', max_length=150)),
                ('cedula_conductor', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_vehiculo', models.CharField(blank=True, default='', max_length=100)),
                ('color_vehiculo', models.CharField(blank=True, default='', max_length=50)),
                ('placa_vehiculo', models.CharField(blank=True, default='', max_length=50)),
                ('beneficiario_autorizado', models.CharField(blank=True, default='', max_length=150)),
                ('cedula_beneficiario', models.CharField(blank=True, default='', max_length=20)),
                ('telefono_beneficiario', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_hora_llegada_conductor', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_llegada_beneficiario', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_despacho', to='core.cotizacion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notas de Despacho',
                'ordering': ['-fecha_despacho'],
            },
        ),
        migrations.CreateModel(
            name='ItemDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.almacen')),
                ('item_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='core.itemcotizacion')),
                ('nota_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.notadespacho')),
            ],
            options={
                'verbose_name_plural': 'Ítems de Despacho',
            },
        ),
        migrations.CreateModel(
            name='NotaDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_devolucion', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('origen_devolucion', models.CharField(blank=True, default='', help_text='Motivo o documento origen de la devolución', max_length=200)),
                ('motivo_devolucion', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('nombre_conductor', models.CharField(blank=True, default='', max_length=150)),
                ('cedula_conductor', models.CharField(blank=True, default='', max_length=20)),
                ('placa_vehiculo', models.CharField(blank=True, default='', max_length=50)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notas de Devolución',
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=50, unique=True, verbose_name='Código/SKU')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de Compra (USD)')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de Venta (USD)')),
                ('activo', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.almacen')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste manual'), ('DEVOLUCION', 'Devolución')], db_index=True, max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('acta_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.actarecepcion')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.almacen')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nota_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.notadespacho')),
                ('nota_devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.notadevolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.producto')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado_fisico', models.CharField(choices=[('BUENO', 'Bueno'), ('DANADO', 'Dañado'), ('OBSOLETO', 'Obsoleto')], default='BUENO', max_length=50)),
                ('motivo', models.TextField()),
                ('almacen_destino', models.ForeignKey(help_text='Almacén que recibe la devolución', on_delete=django.db.models.deletion.PROTECT, to='core.almacen')),
                ('nota_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.notadevolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_devueltos', to='core.producto')),
            ],
            options={
                'verbose_name_plural': 'Ítems de Devolución',
            },
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rif_nit', models.CharField(help_text='Número de identificación fiscal', max_length=50, unique=True, verbose_name='RIF/NIT')),
                ('contacto_principal', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('direccion', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['rif_nit'], name='core_provee_rif_nit_eae948_idx')],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia_pago', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddField(
            model_name='notadevolucion',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_recepcion', to='core.proveedor'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero_rastreo'], name='core_cotiza_numero__013820_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estatus', 'fecha_emision'], name='core_cotiza_estatus_04cd81_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_sku'], name='core_produc_codigo__7efa2d_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['almacen', 'activo'], name='core_produc_almacen_f28d75_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'almacen', '-fecha_movimiento'], name='core_movimi_product_6f9bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo'], name='core_movimi_tipo_24908e_idx'),
        ),
        migrations.AddIndex(
            model_name='actarecepcion',
            index=models.Index(fields=['proveedor', 'fecha_recepcion'], name='core_actare_proveed_31a673_idx'),
        ),
    ]
