# Generated by Django 6.0.6 on 2026-06-04 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rif_nit', models.CharField(max_length=50, unique=True, verbose_name='RIF/NIT')),
                ('contacto_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=50, unique=True, verbose_name='Código/SKU')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rif_nit', models.CharField(max_length=50, unique=True, verbose_name='RIF/NIT')),
                ('contacto_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ActaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura_proveedor', models.CharField(help_text='Número de factura o nota de entrega', max_length=100)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('responsable', models.ForeignKey(help_text='Usuario que recibe la mercancía', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_recepcion', to='core.almacen')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_recepcion', to='core.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Actas de Recepción',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Por Recepción)'), ('SALIDA', 'Salida (Por Despacho)'), ('AJUSTE_POS', 'Ajuste Positivo'), ('AJUSTE_NEG', 'Ajuste Negativo')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('acta_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_recibidos', to='core.actarecepcion')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.almacen')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.producto')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Inventario',
            },
        ),
    ]
