# Generated by Django 6.0.6 on 2026-06-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='formato_pdf',
            field=models.CharField(choices=[('ESTANDAR', 'Estándar (Agrupado por Área)'), ('SUBTOTALES', 'Formato 2 (Con Subtotales por Área)')], default='ESTANDAR', max_length=20, verbose_name='Formato de PDF'),
        ),
    ]
