# Generated by Django 6.0.6 on 2026-06-04 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rastreo', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente por despachar'), ('EN_PROCESO', 'En Proceso (Parcialmente Dotado)'), ('DOTADO', 'Dotado (Completado)'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='core.cliente')),
            ],
            options={
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'verbose_name_plural': 'Ítems de Cotización',
            },
        ),
        migrations.CreateModel(
            name='NotaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=50, unique=True)),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_despacho', to='core.cotizacion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notas de Despacho',
            },
        ),
        migrations.CreateModel(
            name='ItemDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.almacen')),
                ('item_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='core.itemcotizacion')),
                ('nota_despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.notadespacho')),
            ],
            options={
                'verbose_name_plural': 'Ítems de Despacho',
            },
        ),
    ]
