# Generated by Django 6.0.6 on 2026-06-04 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cotizacion_itemcotizacion_notadespacho_itemdespacho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actarecepcion',
            name='monto_total_factura',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total a pagar por esta recepción', max_digits=12),
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia_pago', models.CharField(help_text='Número de transferencia, cheque o recibo', max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.proveedor')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pagos a Proveedores',
            },
        ),
    ]
