# Generated by Django 6.0.6 on 2026-06-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actarecepcion_monto_total_factura_pagoproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
