# Generated by Django 6.0.6 on 2026-06-08 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movimientoinventario_costo_unitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='beneficiario_autorizado',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Beneficiario / Autorizado'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='cedula_beneficiario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='C.I. Beneficiario'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='cedula_conductor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='C.I. Conductor'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='color_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='estado_mercancia',
            field=models.CharField(choices=[('BUENO', 'Buen Estado'), ('CON_OBSERVACIONES', 'Con Observaciones')], default='BUENO', max_length=50),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='fecha_hora_llegada_beneficiario',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Llegada Beneficiario'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='fecha_hora_llegada_conductor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Llegada Conductor'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='institucion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='nombre_conductor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='nro_orden_asociada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Orden Asociada'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='telefono_beneficiario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telf. Beneficiario'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Vehículo'),
        ),
        migrations.AddField(
            model_name='actarecepcion',
            name='ubicacion_almacen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación dentro del Almacén'),
        ),
        migrations.AddField(
            model_name='itemdespacho',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemdespacho',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='nota_despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_despachados', to='core.notadespacho'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='beneficiario_autorizado',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Beneficiario / Autorizado'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='cedula_beneficiario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='C.I. Beneficiario'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='cedula_conductor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='C.I. Conductor'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='color_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='fecha_hora_llegada_beneficiario',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Llegada Beneficiario'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='fecha_hora_llegada_conductor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Llegada Conductor'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='nombre_beneficiario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Beneficiario'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='nombre_conductor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='nro_orden_asociada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Orden Asociada'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='proveedor_origen',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='telefono_beneficiario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telf. Beneficiario'),
        ),
        migrations.AddField(
            model_name='notadespacho',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Vehículo'),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='monto_total_factura',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total a pagar', max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (Por Recepción)'), ('SALIDA', 'Salida (Por Despacho)'), ('DEVOLUCION_APT', 'Reingreso Devolución Apto'), ('DEVOLUCION_DAN', 'Ajuste Devolución Dañado'), ('AJUSTE_POS', 'Ajuste Positivo'), ('AJUSTE_NEG', 'Ajuste Negativo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='numero_guia',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nro. Guía / Despacho'),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='referencia_pago',
            field=models.CharField(help_text='Número de transferencia o recibo', max_length=100),
        ),
        migrations.CreateModel(
            name='NotaDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_devolucion', models.CharField(max_length=50, unique=True, verbose_name='Nro. Devolución (DEV-000000)')),
                ('origen_devolucion', models.CharField(max_length=200, verbose_name='Origen de la Devolución')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('motivo_devolucion', models.TextField(verbose_name='Motivo de la Devolución')),
                ('estado_del_producto', models.CharField(choices=[('APTO', 'Apto para Inventario (Suma al Stock)'), ('DANADO', 'Dañado / Averiado (Va a observaciones, no suma)')], default='APTO', max_length=50)),
                ('nro_orden', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Orden')),
                ('nombre_conductor', models.CharField(blank=True, max_length=150, null=True)),
                ('cedula_conductor', models.CharField(blank=True, max_length=20, null=True, verbose_name='C.I. Conductor')),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Vehículo')),
                ('color_vehiculo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('placa_vehiculo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa')),
                ('beneficiario_autorizado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Beneficiario / Autorizado')),
                ('cedula_beneficiario', models.CharField(blank=True, max_length=20, null=True, verbose_name='C.I. Beneficiario')),
                ('telefono_beneficiario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telf. Beneficiario')),
                ('fecha_hora_llegada_conductor', models.DateTimeField(blank=True, null=True, verbose_name='Llegada Conductor')),
                ('fecha_hora_llegada_beneficiario', models.DateTimeField(blank=True, null=True, verbose_name='Llegada Beneficiario')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notas de Devolución',
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_devueltos', to='core.producto')),
                ('nota_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.notadevolucion')),
            ],
            options={
                'verbose_name_plural': 'Ítems de Devolución',
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='nota_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_devueltos', to='core.notadevolucion'),
        ),
    ]
