# Generated by Django 6.0.6 on 2026-06-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcotizacion',
            old_name='precio_unitario',
            new_name='cantidad_entregada',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='base_imponible_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye_iva',
            field=models.BooleanField(default=True, verbose_name='¿Aplica IVA (16%)?'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='monto_iva_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='observacion_tasa',
            field=models.CharField(default='BCV', help_text='Ej: BCV / 14NOV25', max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='referencia_proyecto',
            field=models.CharField(blank=True, help_text='Ej: LABORATORIO CENTRAL DEL HOSPITAL MILITAR', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal ($)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tasa_bcv',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Tasa Cambio BCV'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Total General (Bs.)'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total ($)'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='cantidad_faltante',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='costo_base_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo real del proveedor', max_digits=12),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='factor_margen',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Margen de ganancia (Ej: 0.10 para 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='observacion_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='pvp_unitario_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='PVP Unitario ($)'),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='seccion_departamento',
            field=models.CharField(default='GENERAL', help_text='Ej: LABORATORIO DE EMERGENCIA / INSTRUMENTAL', max_length=150),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='total_item_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total renglón ($)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_rastreo',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Nro. Nota de Entrega / Cotización'),
        ),
    ]
