# Generated by Django 6.0.6 on 2026-06-08 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_precio_unitario_itemcotizacion_cantidad_entregada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdespacho',
            name='almacen_origen',
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='monto_total_factura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='numero_factura_proveedor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='factor_margen',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Margen de ganancia', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='referencia_pago',
            field=models.CharField(max_length=100),
        ),
    ]
