# Generated by Django 6.0.6 on 2026-06-08 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_itemdespacho_almacen_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdespacho',
            name='almacen_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.almacen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo de Compra (USD)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio de Venta (USD)'),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='beneficiario_autorizado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='cedula_beneficiario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='cedula_conductor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='color_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='fecha_hora_llegada_beneficiario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='fecha_hora_llegada_conductor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='institucion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='nro_orden_asociada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='telefono_beneficiario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actarecepcion',
            name='ubicacion_almacen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='observacion_tasa',
            field=models.CharField(default='BCV', max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='referencia_proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='costo_base_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='factor_margen',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='pvp_unitario_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='seccion_departamento',
            field=models.CharField(default='GENERAL', max_length=150),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='total_item_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='acta_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.actarecepcion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='nota_despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.notadespacho'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='nota_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.notadevolucion'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='beneficiario_autorizado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='cedula_beneficiario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='cedula_conductor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='color_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='fecha_hora_llegada_beneficiario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='fecha_hora_llegada_conductor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='nombre_beneficiario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='nro_orden_asociada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='proveedor_origen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='telefono_beneficiario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notadespacho',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='beneficiario_autorizado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='cedula_beneficiario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='cedula_conductor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='color_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='estado_del_producto',
            field=models.CharField(default='APTO', max_length=50),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='fecha_hora_llegada_beneficiario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='fecha_hora_llegada_conductor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='motivo_devolucion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='nro_devolucion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='nro_orden',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='origen_devolucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='telefono_beneficiario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notadevolucion',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
