# Generated by Django 6.0.6 on 2026-06-08 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_itemdespacho_almacen_origen_producto_costo_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.almacen'),
        ),
    ]
